import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Day Fisioterapia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <Image src="/logo.svg" alt="Day Fisioterapia" width={300} height={200} />
        <h1 className={styles.title}>
          
        </h1>


        <div className={styles.grid}>

      
        </div>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
