import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


const normalizeSrc = (src) => {
  return src[0] === "/" ? src.slice(1) : src;
};

const cloudflareLoader = ({ src, width, quality }) => {
  const params = [`width=${width}`];
  if (quality) {
    params.push(`quality=${quality}`);
  }
  const paramsString = params.join(",");
  return `/cdn-cgi/image/${paramsString}/${normalizeSrc(src)}`;
};


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Day Fisioterapia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <Image loader={cloudflareLoader} src="/logo.svg" alt="Day Fisioterapia" width={300} height={200} />
        <h1 className={styles.title}>
          
        </h1>


        <div className={styles.grid}>

      
        </div>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
